-- Clear all data (respecting FK constraints)
DELETE FROM Rating;
DELETE FROM Event_Staff;
DELETE FROM Resale_Queue;
DELETE FROM Staff;
DELETE FROM Ticket;
DELETE FROM Visitor;
DELETE FROM Band_Member;
DELETE FROM Band;
DELETE FROM Artist_Genre;
DELETE FROM Performance;
DELETE FROM Event;
DELETE FROM Artist;
DELETE FROM Scene;
DELETE FROM Festival;
DELETE FROM Website;
DELETE FROM Location;
DBCC CHECKIDENT ('Location', RESEED, 0);
DBCC CHECKIDENT ('Festival', RESEED, 0);
DBCC CHECKIDENT ('Scene', RESEED, 0);
DBCC CHECKIDENT ('Event', RESEED, 0);
DBCC CHECKIDENT ('Artist', RESEED, 0);
DBCC CHECKIDENT ('Band', RESEED, 0);
DBCC CHECKIDENT ('Performance', RESEED, 0);
DBCC CHECKIDENT ('Visitor', RESEED, 0);
DBCC CHECKIDENT ('Ticket', RESEED, 0);
DBCC CHECKIDENT ('Staff', RESEED, 0);
DBCC CHECKIDENT ('Rating', RESEED, 0);
DBCC CHECKIDENT ('Website', RESEED, 0);
DBCC CHECKIDENT ('Resale_Queue', RESEED, 0);

INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address1', -5.714279, 123.567925, 'City1', 'Country1', 'Continent1');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address2', 34.398984, -60.244235, 'City2', 'Country2', 'Continent2');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address3', 23.516258, 171.123895, 'City3', 'Country3', 'Continent3');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address4', -14.944784, 88.919229, 'City4', 'Country4', 'Continent4');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address5', -76.101822, 116.733440, 'City5', 'Country5', 'Continent5');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address6', -29.309215, 115.104714, 'City6', 'Country6', 'Continent6');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address7', -28.708188, -8.750750, 'City7', 'Country7', 'Continent7');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address8', 77.673950, 81.194049, 'City8', 'Country8', 'Continent8');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address9', -85.275920, 97.559778, 'City9', 'Country9', 'Continent9');
INSERT INTO Location (address, latitude, longitude, city, country, continent) VALUES ('Address10', 28.407245, -116.482055, 'City10', 'Country10', 'Continent10');

-- Festivals
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2017, '2017-07-01', '2017-07-05', 1);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2018, '2018-07-01', '2018-07-05', 2);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2019, '2019-07-01', '2019-07-05', 3);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2020, '2020-07-01', '2020-07-05', 4);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2021, '2021-07-01', '2021-07-05', 5);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2022, '2022-07-01', '2022-07-05', 6);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2023, '2023-07-01', '2023-07-05', 7);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2024, '2024-07-01', '2024-07-05', 8);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2025, '2025-07-01', '2025-07-05', 9);
INSERT INTO Festival (year, start_date, end_date, location_id) VALUES (2026, '2026-07-01', '2026-07-05', 10);

-- Scenes
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene1', 'Description for Scene1', 600, 'Equipment info 1');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene2', 'Description for Scene2', 500, 'Equipment info 2');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene3', 'Description for Scene3', 1000, 'Equipment info 3');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene4', 'Description for Scene4', 800, 'Equipment info 4');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene5', 'Description for Scene5', 600, 'Equipment info 5');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene6', 'Description for Scene6', 800, 'Equipment info 6');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene7', 'Description for Scene7', 800, 'Equipment info 7');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene8', 'Description for Scene8', 400, 'Equipment info 8');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene9', 'Description for Scene9', 500, 'Equipment info 9');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene10', 'Description for Scene10', 1000, 'Equipment info 10');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene11', 'Description for Scene11', 600, 'Equipment info 11');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene12', 'Description for Scene12', 1000, 'Equipment info 12');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene13', 'Description for Scene13', 1000, 'Equipment info 13');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene14', 'Description for Scene14', 500, 'Equipment info 14');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene15', 'Description for Scene15', 1000, 'Equipment info 15');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene16', 'Description for Scene16', 500, 'Equipment info 16');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene17', 'Description for Scene17', 400, 'Equipment info 17');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene18', 'Description for Scene18', 1000, 'Equipment info 18');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene19', 'Description for Scene19', 600, 'Equipment info 19');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene20', 'Description for Scene20', 1000, 'Equipment info 20');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene21', 'Description for Scene21', 800, 'Equipment info 21');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene22', 'Description for Scene22', 1000, 'Equipment info 22');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene23', 'Description for Scene23', 400, 'Equipment info 23');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene24', 'Description for Scene24', 800, 'Equipment info 24');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene25', 'Description for Scene25', 400, 'Equipment info 25');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene26', 'Description for Scene26', 500, 'Equipment info 26');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene27', 'Description for Scene27', 400, 'Equipment info 27');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene28', 'Description for Scene28', 800, 'Equipment info 28');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene29', 'Description for Scene29', 400, 'Equipment info 29');
INSERT INTO Scene (name, description, max_capacity, equipment_info) VALUES ('Scene30', 'Description for Scene30', 800, 'Equipment info 30');

-- Artists
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist1', 'Stage1', '1992-12-01', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist2', 'Stage2', '1986-07-12', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist3', 'Stage3', '2001-11-18', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist4', 'Stage4', '2003-04-18', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist5', 'Stage5', '2004-03-31', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist6', 'Stage6', '1995-02-21', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist7', 'Stage7', '1985-09-19', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist8', 'Stage8', '2005-09-06', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist9', 'Stage9', '1988-11-20', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist10', 'Stage10', '1984-03-07', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist11', 'Stage11', '1980-04-23', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist12', 'Stage12', '1995-09-28', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist13', 'Stage13', '1985-03-04', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist14', 'Stage14', '2004-05-15', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist15', 'Stage15', '1981-02-12', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist16', 'Stage16', '1996-01-15', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist17', 'Stage17', '1981-05-24', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist18', 'Stage18', '1990-01-02', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist19', 'Stage19', '1990-05-20', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist20', 'Stage20', '1997-07-09', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist21', 'Stage21', '1983-10-02', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist22', 'Stage22', '1994-01-12', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist23', 'Stage23', '1981-08-07', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist24', 'Stage24', '1984-02-04', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist25', 'Stage25', '1994-07-12', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist26', 'Stage26', '2000-10-26', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist27', 'Stage27', '1995-02-19', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist28', 'Stage28', '1993-02-20', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist29', 'Stage29', '2003-02-25', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist30', 'Stage30', '2000-08-13', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist31', 'Stage31', '1999-07-09', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist32', 'Stage32', '1986-05-29', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist33', 'Stage33', '1986-09-13', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist34', 'Stage34', '2003-07-04', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist35', 'Stage35', '1996-11-20', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist36', 'Stage36', '2002-10-11', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist37', 'Stage37', '1997-08-28', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist38', 'Stage38', '1991-05-27', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist39', 'Stage39', '1987-01-18', NULL, NULL);
INSERT INTO Artist (name, stage_name, date_of_birth, website, instagram_profile) VALUES ('Artist40', 'Stage40', '2005-07-11', NULL, NULL);

-- Bands
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band1', '2019-11-06', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band2', '2013-06-10', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band3', '2019-07-29', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band4', '2008-12-23', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band5', '2002-11-23', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band6', '2011-08-13', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band7', '2012-02-17', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band8', '2007-06-23', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band9', '2002-06-22', NULL);
INSERT INTO Band (band_name, formation_date, website) VALUES ('Band10', '2004-04-16', NULL);

-- Visitors
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor1', 'Last1', 'v1@example.com', 35);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor2', 'Last2', 'v2@example.com', 43);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor3', 'Last3', 'v3@example.com', 62);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor4', 'Last4', 'v4@example.com', 35);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor5', 'Last5', 'v5@example.com', 33);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor6', 'Last6', 'v6@example.com', 35);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor7', 'Last7', 'v7@example.com', 30);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor8', 'Last8', 'v8@example.com', 43);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor9', 'Last9', 'v9@example.com', 27);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor10', 'Last10', 'v10@example.com', 24);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor11', 'Last11', 'v11@example.com', 45);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor12', 'Last12', 'v12@example.com', 28);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor13', 'Last13', 'v13@example.com', 54);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor14', 'Last14', 'v14@example.com', 59);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor15', 'Last15', 'v15@example.com', 22);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor16', 'Last16', 'v16@example.com', 18);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor17', 'Last17', 'v17@example.com', 58);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor18', 'Last18', 'v18@example.com', 58);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor19', 'Last19', 'v19@example.com', 63);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor20', 'Last20', 'v20@example.com', 41);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor21', 'Last21', 'v21@example.com', 42);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor22', 'Last22', 'v22@example.com', 49);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor23', 'Last23', 'v23@example.com', 59);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor24', 'Last24', 'v24@example.com', 38);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor25', 'Last25', 'v25@example.com', 29);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor26', 'Last26', 'v26@example.com', 26);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor27', 'Last27', 'v27@example.com', 60);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor28', 'Last28', 'v28@example.com', 60);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor29', 'Last29', 'v29@example.com', 36);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor30', 'Last30', 'v30@example.com', 58);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor31', 'Last31', 'v31@example.com', 56);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor32', 'Last32', 'v32@example.com', 19);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor33', 'Last33', 'v33@example.com', 24);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor34', 'Last34', 'v34@example.com', 42);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor35', 'Last35', 'v35@example.com', 59);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor36', 'Last36', 'v36@example.com', 57);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor37', 'Last37', 'v37@example.com', 34);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor38', 'Last38', 'v38@example.com', 53);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor39', 'Last39', 'v39@example.com', 59);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor40', 'Last40', 'v40@example.com', 60);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor41', 'Last41', 'v41@example.com', 30);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor42', 'Last42', 'v42@example.com', 27);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor43', 'Last43', 'v43@example.com', 65);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor44', 'Last44', 'v44@example.com', 40);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor45', 'Last45', 'v45@example.com', 54);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor46', 'Last46', 'v46@example.com', 65);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor47', 'Last47', 'v47@example.com', 52);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor48', 'Last48', 'v48@example.com', 57);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor49', 'Last49', 'v49@example.com', 43);
INSERT INTO Visitor (first_name, last_name, contact, age) VALUES ('Visitor50', 'Last50', 'v50@example.com', 62);

-- Events
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (7, 1, '2021-10-12');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (4, 2, '2020-06-25');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (4, 3, '2020-06-28');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (7, 4, '2018-12-20');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (7, 5, '2024-11-16');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (8, 6, '2024-09-12');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (10, 7, '2019-09-06');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (3, 8, '2021-02-23');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (8, 9, '2017-10-31');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (6, 10, '2019-05-23');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (1, 11, '2020-07-04');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (4, 12, '2025-05-07');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (8, 13, '2025-07-09');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (4, 14, '2023-01-02');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (5, 15, '2018-10-21');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (8, 16, '2022-08-29');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (5, 17, '2022-05-30');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (2, 18, '2017-12-10');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (4, 19, '2017-08-14');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (1, 20, '2026-09-14');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (9, 21, '2017-02-25');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (7, 22, '2027-08-08');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (4, 23, '2027-06-02');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (2, 24, '2023-01-12');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (6, 25, '2025-03-14');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (9, 26, '2027-04-17');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (5, 27, '2025-03-17');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (4, 28, '2021-08-22');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (2, 29, '2026-07-14');
INSERT INTO Event (festival_id, scene_id, event_date) VALUES (7, 30, '2027-07-14');

-- Performances
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (21, 18, NULL, 'headline', '16:00', '01:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (20, 22, NULL, 'headline', '16:00', '02:00:00', '00:18:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (24, 34, NULL, 'headline', '16:00', '01:00:00', '00:06:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (3, NULL, 6, 'headline', '21:00', '02:00:00', '00:17:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (3, NULL, 6, 'headline', '20:00', '01:00:00', '00:10:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (27, NULL, 6, 'Special guest', '22:00', '02:00:00', '00:06:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (16, 19, NULL, 'warm up', '16:00', '01:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (3, 34, NULL, 'warm up', '21:00', '02:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (5, 7, NULL, 'headline', '16:00', '01:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (7, 35, NULL, 'warm up', '17:00', '02:00:00', '00:14:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (9, NULL, 5, 'warm up', '19:00', '01:00:00', '00:19:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (7, 3, NULL, 'warm up', '21:00', '02:00:00', '00:12:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (20, 39, NULL, 'headline', '22:00', '02:00:00', '00:12:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (10, 2, NULL, 'warm up', '22:00', '01:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (3, 24, NULL, 'warm up', '16:00', '01:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (12, 28, NULL, 'warm up', '20:00', '02:00:00', '00:17:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (14, 1, NULL, 'Special guest', '19:00', '01:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (5, NULL, 2, 'headline', '17:00', '01:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (1, 2, NULL, 'headline', '22:00', '02:00:00', '00:20:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (11, 16, NULL, 'headline', '22:00', '02:00:00', '00:18:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (14, NULL, 1, 'headline', '16:00', '01:00:00', '00:17:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (23, NULL, 5, 'Special guest', '20:00', '02:00:00', '00:19:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (21, NULL, 2, 'Special guest', '22:00', '01:00:00', '00:18:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (17, NULL, 4, 'warm up', '18:00', '02:00:00', '00:14:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, NULL, 2, 'headline', '18:00', '01:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (12, NULL, 4, 'Special guest', '22:00', '02:00:00', '00:10:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (19, NULL, 3, 'Special guest', '16:00', '02:00:00', '00:14:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (6, NULL, 1, 'Special guest', '19:00', '02:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (19, 19, NULL, 'headline', '19:00', '02:00:00', '00:16:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (19, 37, NULL, 'warm up', '16:00', '01:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (7, NULL, 9, 'Special guest', '21:00', '02:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (19, NULL, 6, 'headline', '21:00', '02:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (26, 24, NULL, 'Special guest', '16:00', '01:00:00', '00:17:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (13, NULL, 9, 'headline', '20:00', '01:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (26, NULL, 8, 'headline', '22:00', '02:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (26, 6, NULL, 'warm up', '22:00', '02:00:00', '00:16:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (6, NULL, 8, 'Special guest', '18:00', '02:00:00', '00:06:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (21, 12, NULL, 'Special guest', '22:00', '01:00:00', '00:18:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, 4, NULL, 'Special guest', '20:00', '02:00:00', '00:11:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (16, NULL, 6, 'headline', '21:00', '02:00:00', '00:06:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (13, NULL, 3, 'headline', '18:00', '02:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (13, NULL, 8, 'warm up', '17:00', '01:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (9, 33, NULL, 'warm up', '21:00', '01:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (3, 34, NULL, 'warm up', '20:00', '01:00:00', '00:19:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (29, 25, NULL, 'warm up', '19:00', '01:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (21, NULL, 6, 'warm up', '21:00', '02:00:00', '00:19:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (9, 23, NULL, 'headline', '20:00', '01:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (7, NULL, 4, 'warm up', '20:00', '01:00:00', '00:06:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (4, NULL, 10, 'Special guest', '19:00', '01:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (7, 14, NULL, 'headline', '17:00', '01:00:00', '00:16:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (30, 35, NULL, 'Special guest', '17:00', '01:00:00', '00:13:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (21, 3, NULL, 'headline', '18:00', '01:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (14, 24, NULL, 'Special guest', '22:00', '01:00:00', '00:16:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, NULL, 9, 'warm up', '19:00', '01:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (9, 18, NULL, 'warm up', '19:00', '02:00:00', '00:07:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (14, 3, NULL, 'warm up', '18:00', '01:00:00', '00:12:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (30, NULL, 6, 'warm up', '19:00', '02:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (10, NULL, 4, 'Special guest', '21:00', '02:00:00', '00:20:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (11, 30, NULL, 'headline', '18:00', '01:00:00', '00:20:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (29, 13, NULL, 'headline', '18:00', '02:00:00', '00:18:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (15, NULL, 1, 'headline', '19:00', '01:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (7, NULL, 2, 'Special guest', '21:00', '02:00:00', '00:11:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (21, NULL, 6, 'warm up', '21:00', '01:00:00', '00:20:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (6, 13, NULL, 'Special guest', '20:00', '02:00:00', '00:08:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (12, 39, NULL, 'Special guest', '16:00', '01:00:00', '00:16:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (8, NULL, 5, 'Special guest', '20:00', '01:00:00', '00:18:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (24, NULL, 5, 'warm up', '21:00', '02:00:00', '00:10:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, 3, NULL, 'Special guest', '17:00', '02:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (19, 6, NULL, 'headline', '22:00', '02:00:00', '00:12:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (11, NULL, 3, 'Special guest', '21:00', '01:00:00', '00:12:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, 10, NULL, 'headline', '21:00', '01:00:00', '00:16:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (13, NULL, 1, 'headline', '17:00', '02:00:00', '00:06:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (16, 22, NULL, 'headline', '20:00', '01:00:00', '00:07:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, 4, NULL, 'headline', '19:00', '01:00:00', '00:08:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (17, NULL, 9, 'warm up', '19:00', '02:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, 14, NULL, 'Special guest', '21:00', '02:00:00', '00:20:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (5, 33, NULL, 'headline', '16:00', '01:00:00', '00:16:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (5, 10, NULL, 'headline', '21:00', '02:00:00', '00:19:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (20, NULL, 9, 'headline', '20:00', '02:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (10, NULL, 10, 'headline', '22:00', '02:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (21, NULL, 2, 'Special guest', '19:00', '02:00:00', '00:11:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (16, 19, NULL, 'headline', '19:00', '01:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (20, 36, NULL, 'headline', '17:00', '01:00:00', '00:17:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (18, NULL, 3, 'Special guest', '19:00', '02:00:00', '00:07:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (27, 7, NULL, 'headline', '21:00', '01:00:00', '00:05:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (8, NULL, 7, 'headline', '17:00', '02:00:00', '00:06:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (20, NULL, 1, 'headline', '19:00', '01:00:00', '00:19:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (3, 29, NULL, 'warm up', '18:00', '02:00:00', '00:10:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (16, 15, NULL, 'warm up', '20:00', '02:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (8, 37, NULL, 'warm up', '20:00', '02:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (27, NULL, 8, 'warm up', '20:00', '01:00:00', '00:12:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (24, 15, NULL, 'warm up', '22:00', '01:00:00', '00:12:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (3, NULL, 1, 'headline', '21:00', '02:00:00', '00:08:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (28, NULL, 5, 'headline', '18:00', '01:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (8, 37, NULL, 'warm up', '21:00', '01:00:00', '00:09:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (2, NULL, 5, 'headline', '16:00', '02:00:00', '00:15:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (4, NULL, 9, 'warm up', '19:00', '01:00:00', '00:18:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (20, NULL, 5, 'Special guest', '21:00', '01:00:00', '00:20:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (13, 15, NULL, 'warm up', '21:00', '02:00:00', '00:08:00');
INSERT INTO Performance (event_id, artist_id, band_id, performance_type, start_time, duration, break_duration) VALUES (17, NULL, 6, 'Special guest', '18:00', '01:00:00', '00:12:00');

-- Tickets
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (16, 30, '2022-06-16', 104.84, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (26, 24, '2024-02-18', 87.59, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (5, 1, '2020-09-24', 31.4, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 39, '2021-09-01', 28.98, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (4, 43, '2021-03-19', 40.31, 'debit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 7, '2020-12-28', 21.29, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (3, 46, '2023-05-06', 46.23, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 39, '2021-03-24', 113.37, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 35, '2021-09-03', 85.13, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 50, '2020-08-13', 47.96, 'credit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (27, 10, '2024-03-21', 52.17, 'debit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (21, 45, '2022-12-06', 28.39, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 49, '2021-12-05', 46.29, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (12, 32, '2022-09-19', 119.23, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (5, 12, '2022-02-24', 78.68, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 48, '2025-02-18', 29.56, 'bank transfer', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 50, '2024-07-21', 108.46, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (10, 3, '2022-08-23', 99.69, 'bank transfer', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (30, 39, '2023-03-12', 43.37, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (4, 7, '2027-06-26', 22.35, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (12, 13, '2026-12-15', 64.45, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (30, 5, '2027-07-19', 101.02, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 33, '2025-01-29', 97.28, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 12, '2020-12-27', 78.9, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 33, '2024-05-02', 87.58, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 21, '2022-11-04', 110.42, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 34, '2020-04-05', 54.57, 'not cash', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 26, '2020-09-09', 85.12, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 15, '2024-01-21', 28.78, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (13, 24, '2020-05-18', 76.78, 'credit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 38, '2021-03-05', 64.83, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (13, 18, '2027-07-08', 112.28, 'credit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 20, '2021-01-18', 24.83, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (11, 47, '2020-12-06', 54.33, 'credit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 38, '2022-05-25', 93.87, 'not cash', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 27, '2020-11-09', 61.7, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (7, 35, '2020-02-08', 24.81, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (25, 32, '2024-10-20', 30.55, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 41, '2022-01-14', 87.09, 'not cash', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (21, 44, '2026-03-15', 102.35, 'not cash', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 24, '2023-01-27', 45.65, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 46, '2025-03-31', 40.8, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (29, 14, '2020-05-15', 22.28, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (6, 48, '2020-02-16', 115.81, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (6, 25, '2026-06-06', 68.1, 'not cash', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 48, '2025-11-03', 77.35, 'credit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 27, '2025-04-15', 26.4, 'bank transfer', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 14, '2022-02-17', 34.9, 'debit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (3, 1, '2025-12-28', 107.57, 'credit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 34, '2020-09-03', 64.15, 'credit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 14, '2025-08-28', 101.1, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (7, 44, '2022-03-10', 76.67, 'bank transfer', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 11, '2027-03-26', 112.31, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (10, 31, '2023-10-31', 77.97, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (30, 24, '2024-08-15', 25.48, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 4, '2026-12-01', 83.47, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (3, 34, '2022-12-01', 76.11, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (28, 37, '2023-09-02', 69.96, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (4, 18, '2024-09-08', 91.84, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (20, 11, '2025-12-04', 105.08, 'credit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (16, 11, '2025-12-02', 78.34, 'debit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 38, '2022-02-27', 89.67, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (24, 15, '2027-09-15', 75.83, 'credit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (6, 21, '2026-03-21', 113.83, 'not cash', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (28, 4, '2020-03-01', 25.9, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 7, '2022-07-20', 26.86, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 6, '2024-05-16', 88.65, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 28, '2024-09-20', 57.91, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (26, 41, '2022-09-04', 103.94, 'credit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 6, '2021-03-21', 47.93, 'bank transfer', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 43, '2026-04-27', 36.01, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (16, 13, '2026-08-24', 44.18, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 24, '2026-12-03', 99.8, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (3, 39, '2021-07-31', 78.05, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (6, 28, '2022-04-23', 97.36, 'not cash', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (6, 33, '2022-10-13', 93.41, 'not cash', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (13, 34, '2025-09-13', 70.02, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 9, '2021-01-07', 43.54, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (12, 30, '2026-12-04', 101.35, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (12, 35, '2023-11-16', 63.46, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 8, '2025-07-25', 70.62, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (13, 37, '2020-03-29', 109.94, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 23, '2027-05-11', 107.15, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (7, 32, '2020-08-16', 106.52, 'credit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (10, 47, '2025-10-30', 114.23, 'not cash', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 3, '2026-08-21', 85.89, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 7, '2022-07-16', 51.02, 'credit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (11, 34, '2025-07-27', 99.82, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 28, '2023-08-31', 96.63, 'credit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 44, '2023-02-23', 98.06, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 24, '2020-06-29', 108.72, 'debit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (29, 23, '2024-04-12', 29.71, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 26, '2022-07-08', 67.88, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (25, 39, '2025-06-19', 29.43, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (25, 21, '2020-01-31', 84.31, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 3, '2022-02-19', 108.88, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 27, '2027-05-20', 88.45, 'debit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 20, '2024-12-29', 98.72, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 47, '2021-08-29', 91.39, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 34, '2022-05-08', 101.56, 'not cash', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (7, 39, '2022-06-01', 93.81, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 2, '2025-12-14', 28.43, 'debit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 49, '2023-01-16', 24.23, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 40, '2020-05-03', 97.14, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (12, 34, '2024-04-18', 112.0, 'credit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 15, '2024-11-07', 38.63, 'bank transfer', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 10, '2022-12-21', 59.68, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (11, 4, '2022-07-23', 105.73, 'credit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 45, '2022-09-20', 31.83, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 10, '2024-10-15', 44.07, 'credit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (27, 32, '2024-01-21', 110.02, 'not cash', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 10, '2027-11-05', 60.74, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 23, '2025-04-18', 92.6, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (4, 11, '2026-11-08', 73.06, 'bank transfer', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 10, '2023-05-20', 34.81, 'bank transfer', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (16, 3, '2025-10-12', 82.47, 'debit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (21, 42, '2021-07-24', 119.42, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 43, '2020-06-07', 70.86, 'credit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 23, '2025-06-16', 72.76, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (20, 18, '2022-03-09', 113.38, 'credit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 20, '2026-12-01', 117.13, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (24, 39, '2020-09-30', 82.3, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (11, 48, '2026-03-26', 86.77, 'bank transfer', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 16, '2023-05-16', 54.32, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 49, '2025-10-08', 104.27, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (10, 39, '2022-06-14', 79.36, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 36, '2025-06-02', 89.09, 'credit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (24, 47, '2021-05-25', 38.33, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (5, 33, '2020-11-12', 64.47, 'debit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 50, '2023-03-25', 40.25, 'credit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (12, 6, '2022-03-10', 25.64, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (24, 14, '2023-01-21', 91.96, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (5, 5, '2026-02-28', 52.75, 'not cash', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (30, 33, '2021-12-28', 39.09, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (26, 35, '2024-08-08', 100.68, 'credit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 41, '2025-11-02', 81.43, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (29, 41, '2026-03-01', 77.12, 'credit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 32, '2021-11-29', 56.59, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (6, 22, '2026-12-04', 25.08, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 37, '2024-05-25', 85.68, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (7, 13, '2026-01-18', 26.02, 'credit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 30, '2023-03-13', 69.3, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (12, 5, '2023-05-07', 70.1, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (4, 25, '2026-07-20', 84.79, 'credit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (4, 10, '2022-01-26', 97.4, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (10, 11, '2024-07-14', 52.32, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (5, 7, '2024-03-11', 51.36, 'debit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 18, '2025-07-29', 106.95, 'bank transfer', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (5, 16, '2027-06-03', 114.65, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 46, '2024-04-30', 118.02, 'credit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (25, 1, '2025-12-13', 86.34, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 49, '2025-12-31', 83.22, 'bank transfer', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (15, 45, '2025-07-05', 35.19, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 7, '2021-04-27', 20.08, 'debit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (24, 49, '2025-04-16', 78.81, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (2, 14, '2021-10-06', 114.85, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 38, '2027-02-16', 76.52, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (3, 29, '2025-06-02', 60.04, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 38, '2021-06-23', 37.29, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 49, '2027-03-26', 80.61, 'credit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 35, '2026-06-15', 102.04, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (28, 28, '2025-11-20', 99.49, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (20, 22, '2024-10-29', 73.64, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 31, '2023-03-08', 91.43, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (13, 36, '2026-07-01', 90.15, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (3, 28, '2026-04-09', 69.86, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 14, '2025-10-26', 78.21, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (29, 3, '2020-09-28', 43.99, 'bank transfer', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 3, '2024-10-20', 36.59, 'credit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (29, 30, '2020-11-24', 20.98, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (13, 46, '2020-03-13', 29.76, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (11, 30, '2027-12-11', 115.14, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (1, 15, '2020-01-02', 33.19, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (23, 9, '2020-03-27', 24.58, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 16, '2026-08-31', 41.67, 'debit card', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 5, '2025-12-11', 28.02, 'debit card', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 8, '2026-08-28', 61.29, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (5, 40, '2025-03-04', 81.07, 'credit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 10, '2026-09-11', 20.12, 'credit card', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (20, 40, '2023-04-26', 68.2, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (3, 24, '2022-05-09', 92.28, 'bank transfer', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (19, 8, '2025-06-27', 104.69, 'not cash', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (7, 30, '2023-08-28', 80.81, 'bank transfer', NULL, 'Regular', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 16, '2027-06-17', 103.48, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 40, '2024-07-17', 93.92, 'not cash', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (18, 43, '2026-03-05', 102.3, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 38, '2026-12-27', 101.57, 'not cash', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (9, 19, '2024-03-13', 86.83, 'credit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (14, 10, '2025-08-02', 30.55, 'bank transfer', NULL, 'VIP', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (10, 9, '2025-11-21', 43.32, 'not cash', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (7, 21, '2026-05-04', 50.67, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (8, 50, '2024-10-04', 89.5, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (27, 15, '2024-12-20', 32.04, 'credit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (11, 28, '2022-08-25', 56.97, 'debit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (25, 15, '2020-09-25', 42.25, 'bank transfer', NULL, 'Student', 1);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (22, 37, '2027-05-04', 93.41, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (6, 18, '2020-11-07', 36.02, 'bank transfer', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 13, '2020-08-28', 79.74, 'credit card', NULL, 'Student', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (20, 1, '2024-07-13', 96.33, 'debit card', NULL, 'VIP', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (10, 19, '2020-07-21', 68.3, 'debit card', NULL, 'Regular', 0);
INSERT INTO Ticket (event_id, visitor_id, purchase_date, cost, payment_method, ean, ticket_category, used) VALUES (17, 11, '2023-09-14', 42.63, 'bank transfer', NULL, 'VIP', 1);
